package com.myhostel.entity;
// Generated Dec 27, 2018 1:02:45 AM by Hibernate Tools 4.3.1



/**
 * CostList generated by hbm2java
 */
public class CostList  implements java.io.Serializable {


     private Integer slNo;
     private String member;
     private int memberId;
     private String date;
     private int cost;

    public CostList() {
    }

    public CostList(String member, int memberId, String date, int cost) {
       this.member = member;
       this.memberId = memberId;
       this.date = date;
       this.cost = cost;
    }
   
    public Integer getSlNo() {
        return this.slNo;
    }
    
    public void setSlNo(Integer slNo) {
        this.slNo = slNo;
    }
    public String getMember() {
        return this.member;
    }
    
    public void setMember(String member) {
        this.member = member;
    }
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public int getCost() {
        return this.cost;
    }
    
    public void setCost(int cost) {
        this.cost = cost;
    }




}


